// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJudPbnmWHkJDjeaq1KwLASyyHPXQhAa8',
    appId: '1:89723410688:android:88356904253bced91c7be5',
    messagingSenderId: '89723410688',
    projectId: 'flutter-insta-289b5',
    storageBucket: 'flutter-insta-289b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Swsh83AijR3lYG304Oyn-AlqHpBdK7c',
    appId: '1:89723410688:ios:0d78d562628542281c7be5',
    messagingSenderId: '89723410688',
    projectId: 'flutter-insta-289b5',
    storageBucket: 'flutter-insta-289b5.appspot.com',
    iosClientId: '89723410688-cc98m58pg5p6nkvqt8apaokc5bqvoqtl.apps.googleusercontent.com',
    iosBundleId: 'com.rio.flutterinsta',
  );
}
